### ISSUE TITLE
Not available via Composer

### ISSUE THREAD

**Issue by deviationist** [ScadaExposure/Shodan-PHP-REST-API#3]
Hello!
Thanks for creating this, very helpful. But this repository is not present on packagist.org and can therefore not be pulled in via Composer. Do you guys have any plans to publish this as a Composer-package? Would be very helpful in cases when one would implement the Shodan-class into ones own project.

Best regards
Robert S.

**Comment by isgroup-srl** [comment]
Hi @roberts91 good idea, feel free to create a pull request for the `composer.json` file!
